/*
 * This source file was generated by the Gradle 'init' task
 */
package org.utils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDate;

import org.utils.WorkLogConfig;

class WorkLogConfigTest {
    @Test
    void methodRunLibraryReturnsTrue() {
        WorkLogConfig classUnderTest = new WorkLogConfig();
        assertDoesNotThrow(() -> classUnderTest.run(), "run() should execute without throwing an exception");
    }

    @Test
    void accessibleMethodExists() {
        assertDoesNotThrow(() -> {
            // Tell reflection exactly what parameters to look for
            WorkLogConfig.class.getDeclaredMethod("isValidDateRange", LocalDate.class, LocalDate.class);
        }, "The method isValidDateRange(LocalDate, LocalDate) should exist in WorkLogConfig");
    }
}
