/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import nl.littlerobots.vcu.plugin.versionSelector

plugins {
  alias(libs.plugins.spotless)
  alias(libs.plugins.catalogUpdate)
  alias(libs.plugins.versionUpdate)
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

spotless {
  kotlinGradle {
    target("*.gradle.kts") // Target all Kotlin DSL build scripts
    ktfmt().googleStyle() // Use ktfmt or ktlint
  }
}

// LATEST to accept any latest version, STABLE to select only stable versions or
// PREFER_STABLE (default setting) to accept unstable versions only if the catalog already uses an unstable version
versionCatalogUpdate {
    versionSelector {
        // here 'it' is a ModuleVersionCandidate that can be used to determine if the version
        // is allowed, returning true if it is.
        !(it.candidate.version.contains("SNAPSHOT") || it.candidate.version.contains("ALPHA"))
    }
}