name: 'Java Build and Test'
description: 'Sets up Java 25, configures Gradle, builds the project and creates the Fat JAR.'
inputs:
  java-version:
    description: 'The Java JDK version to use'
    required: false
    default: '25'
  working-directory:
    description: 'The root directory of the Java project'
    required: false
    default: .
outputs:
  app-utils-version:
    description: 'version being created'
    value: ${{ steps.build.outputs.app-utils-version }}
  app-utils-fat-jar:
    description: 'Path to the generated Fat JAR artifact'
    value: ${{ steps.build.outputs.app-utils-fat-jar }}

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      # https://github.com/marketplace/actions/setup-java-jdk?version=v5.0.0
      with:
        distribution: 'microsoft'
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      # https://github.com/gradle/actions/blob/main/README.md

    - name: Test Suite with Gradle
      id: test
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        gradle wrapper
        chmod +x gradlew
        echo "================= Executing Test Suite =================="
        ./gradlew test

    - name: Build the Fat JAR Test with Gradle
      id: build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        gradle wrapper
        chmod +x gradlew
        echo "================= checking location $PWD =================="
        ls -lha
        echo "================= Building the project and creating the Fat JAR =================="
        ./gradlew clean build shadowJar
        UTIL_APP_VERSION=$(./gradlew -q getVersion)
        UTIL_JAR_NAME="lib-$UTIL_APP_VERSION-all.jar"
        echo "app-utils-version=$UTIL_APP_VERSION" >> $GITHUB_OUTPUT
        echo "app-utils-fat-jar=$UTIL_JAR_NAME" >> $GITHUB_OUTPUT
        echo "================= completed Build the Fat JAR =================="
