/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.utils.WorkLogConfig;

class WorkLogConfigTest {
    @Test void someLibraryMethodReturnsTrue() {
        WorkLogConfig classUnderTest = new WorkLogConfig();
        assertDoesNotThrow(() -> classUnderTest.run(), "run() should execute without throwing an exception");
    }

    @Test void publicHolidaysMethodExists() {
        assertDoesNotThrow(WorkLogConfig::printHolidays, "printHolidays() should be available");
    }
}
