name: Java Utilities CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "java-utilities/**"
      - ".github/workflows/ci-cd-java-utilities.yml"
      - ".github/actions/java-build-test/**"
    tags:
      - "v*.*.*" # semVer tags trigger release job v1.0.0
  pull_request:
    branches: ["main"]
    paths:
      - "java-utilities/**"
  workflow_dispatch:

permissions:
  contents: write # Needed for creating GitHub Releases

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github Repository
        uses: actions/checkout@v6.0.2
        # https://github.com/marketplace/actions/checkout
        # with:
        #   # CRITICAL: Axion needs the full git history to calculate versions
        #   fetch-depth: 0

      - name: Build Java Utilities
        uses: ./.github/actions/java-build-test
        with:
          java-version: "25"
          working-directory: .

      - name: Upload Fat JAR Artifact
        uses: actions/upload-artifact@v7.0.1
        # https://github.com/marketplace/actions/upload-a-build-artifact
        with:
          name: java-utilities-fat-jar
          path: java-utilities/lib/build/libs/lib-*-all.jar
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial for creating a GitHub Release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Print TODO for JGit Signing
        run: |
          echo "====================================================================================="
          echo "🚨 HUGE TODO: CREATE A GITHUB ISSUE IN THE PLUGIN PROVIDER (axion-release-plugin) 🚨"
          echo "TO PROPERLY HANDLE GPG SIGNING WITH JGIT OR DELEGATE TO EXTERNAL GPG."
          echo ""
          echo "Assumption: The release is done manually and the git tag is signed from the local"
          echo "laptop once a pull request is merged to main."
          echo "====================================================================================="

      - name: Verify Version Calculation
        run: |
          echo "====================================================================================="
          echo "🚨 TODO:  🚨"

      - name: Download Fat JAR Artifact
        uses: actions/download-artifact@v8.0.1
        # https://github.com/marketplace/actions/download-a-build-artifact
        with:
          name: java-utilities-fat-jar # todo: use name from upload step output
          path: .

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v3.0.0
        # https://github.com/marketplace/actions/gh-release
        with:
          generate_release_notes: true
          files: lib-*-all.jar
