name: Github Repos Reporter
permissions:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#defining-access-for-the-github_token-scopes
  actions: read
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
    inputs:
      repo_filter:
        description: "Optional substring to filter repositories (case-insensitive)"
        required: false
        type: string

jobs:
  report-all-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5.0.1

      - name: Validate GitHub Token
        uses: ./.github/actions/validate-gh-token
        with:
          gh_token: ${{ secrets.ORG_LEVEL_TOKEN }}

      - name: Report Repos
        uses: ./.github/actions/report-repos
        with:
          repo_filter: ${{ inputs.repo_filter }}
          org_name: ${{ github.repository_owner }}
          gh_token: ${{ secrets.ORG_LEVEL_TOKEN }}
